language: node_js
node_js:
  - "10"
script: 
  - echo "hello world"
install:
  - yarn install
  - yarn run generate
cache:
  directories:
    - node_modules
# after_script:
#   - cd ./dist
#   - git init
#   - git config user.name "imnginx"
#   - git config user.email "xenry@163.com"
#   - git add .
#   - git commit -m "automated build"
#   - git push --quiet --force https://git.dev.tencent.com/imnginx/use.git master